{
    "NineManga":{
      "baseUrl":"https://en.ninemanga.com",
    },   
    "Manga365":{
      "baseUrl":"https://365manga.com",
    },    
    "Manga1stKiss":{
      "baseUrl":"https://1stkissmanga.io",
    },
    "MangaFunny":{
      "baseUrl":"https://mangafunny.org",
    } 
}
